services:
  - type: web
    name: kupujemy-bot
    runtime: node
    rootDir: bot
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: ORDER_API_KEY
        sync: false
